name: 构建容器镜像

on:
  workflow_dispatch: # 手动触发

  # 创建 v 开头的 tag 时触发
  push:
    tags:
      - v*

env:
  REGISTRY: ${{ vars.REGISTRY }}
  IMAGE: ${{ vars.IMAGE }}
  ARCH: amd64

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 这里用于定义 GITHUB_TOKEN 的权限
    permissions:
      packages: write
      contents: read

    steps:
      - name: 设置环境变量
        run: |
          echo "REGISTRY_USERNAME=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//')" >> $GITHUB_ENV

      - name: 检查环境变量
        run: |
          echo "REGISTRY:          ${{ env.REGISTRY }}"
          echo "IMAGE:             ${{ env.IMAGE }}"
          echo "REGISTRY_USERNAME: ${{ env.REGISTRY_USERNAME }}"
          echo "ARCH:              ${{ env.ARCH }}"
          echo "VERSION:           ${{ env.VERSION }}"

      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_REF }}

      # 配置 QEMU 和 buildx 用于多架构镜像的构建
      - name: 配置 QEMU 环境
        uses: docker/setup-qemu-action@v3

      - name: 配置容器环境
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: 检查构建器
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      # 根据输入自动生成 tag 和 label 等数据
      - name: 构建容器元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: 检查容器元数据
        run: |
          echo "docker iamge tags:    ${{ steps.meta.outputs.tags }}"
          echo "docker iamge labels:  ${{ steps.meta.outputs.labels }}"
          echo "docker iamge version: ${{ steps.meta.outputs.version }}"

      # 缓存 Docker 镜像以加速构建
      - name: 配置容器缓存层
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 登录到容器仓库
      # github secrets.GITHUB_TOKEN 不需要手动添加，可以直接使用
      - name: 登录容器注册表
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 构建并上传
      - name: 构建容器并推送注册表
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          push: true
          build-args: |
            ARCH=${{ env.ARCH }}
            VERSION=${{ env.VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: 检查镜像
        run: |
          docker buildx imagetools inspect \
          ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.meta.outputs.version }}
